version: "3.9"
services:
  web:
    container_name: CowWeb
    build: .
    ports:
      - "3000:3000"
    links:
      - monguito
  monguito:
    image: mongo
    ports: 
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=3x@47c2ldv[KRx9b
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: